name: cw_sdk_dart
version: 0.1.1-alpha.1
description: An unofficial sdk for the Cryptowatch API, currently in alpha. Features full support for the REST API.
homepage: https://github.com/infinitycounter/cw-sdk-dart

environment:
  sdk: ">=2.4.0 <3.0.0"

dependencies:
  http: ^0.12.1
  test: ^1.14.3
  quiver: ^2.1.3
  collection: ^1.14.12